package gg.lakehouse.cctv.camera;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import gg.lakehouse.cctv.CCTV;
import org.joml.Matrix4f;
import org.joml.Vector3f;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.GZIPInputStream;

/**
 * The exported model-layer geometry pack (assets/cctv/entity_geometry.json.gz,
 * generated by the dev client): part trees with default poses and
 * polygon-level vertices for every entity AND block-entity model layer —
 * chests, shulkers, signs and friends live in the same layer system. Loaded
 * from the mod jar, so both the client and the dedicated-server camera
 * pipelines share it.
 */
public final class GeometryPack {
    public record Part(float x, float y, float z, float xr, float yr, float zr,
                       float[][][] quads, Map<String, Part> children) {
    }

    private static volatile Map<String, Part> layers;

    private GeometryPack() {
    }

    public static Map<String, Part> layers() {
        var loaded = layers;
        if (loaded != null) return loaded;
        synchronized (GeometryPack.class) {
            if (layers == null) layers = load();
            return layers;
        }
    }

    private static Map<String, Part> load() {
        var result = new HashMap<String, Part>();
        try (InputStream raw = GeometryPack.class.getResourceAsStream("/assets/cctv/entity_geometry.json.gz")) {
            if (raw == null) {
                CCTV.LOGGER.warn("Geometry pack missing from the mod jar");
                return result;
            }
            try (var in = new GZIPInputStream(raw)) {
                var json = JsonParser.parseString(new String(in.readAllBytes(), StandardCharsets.UTF_8)).getAsJsonObject();
                for (var entry : json.getAsJsonObject("layers").entrySet()) {
                    result.put(entry.getKey(), parsePart(entry.getValue().getAsJsonObject()));
                }
            }
            CCTV.LOGGER.info("Loaded geometry pack: {} layers", result.size());
        } catch (Exception e) {
            CCTV.LOGGER.error("Failed to load the geometry pack", e);
        }
        return result;
    }

    /** Merges a dropped-in pack (e.g. cctv-assets/entity_geometry.json.gz with modded layers) over the bundled one. */
    public static void overlay(java.nio.file.Path file) {
        if (!java.nio.file.Files.isRegularFile(file)) return;
        try (var in = new GZIPInputStream(java.nio.file.Files.newInputStream(file))) {
            var json = JsonParser.parseString(new String(in.readAllBytes(), StandardCharsets.UTF_8)).getAsJsonObject();
            var target = layers();
            int before = target.size();
            for (var entry : json.getAsJsonObject("layers").entrySet()) {
                target.put(entry.getKey(), parsePart(entry.getValue().getAsJsonObject()));
            }
            CCTV.LOGGER.info("Overlaid geometry pack {}: {} layers ({} new)", file, target.size(), target.size() - before);
        } catch (Exception e) {
            CCTV.LOGGER.error("Failed to overlay geometry pack {}", file, e);
        }
    }

    private static Part parsePart(JsonObject json) {
        float[][][] quads = new float[0][][];
        if (json.has("quads")) {
            var array = json.getAsJsonArray("quads");
            quads = new float[array.size()][4][5];
            for (int q = 0; q < array.size(); q++) {
                var quad = array.get(q).getAsJsonArray();
                for (int v = 0; v < 4; v++) {
                    var vertex = quad.get(v).getAsJsonArray();
                    for (int i = 0; i < 5; i++) quads[q][v][i] = vertex.get(i).getAsFloat();
                }
            }
        }
        var children = new HashMap<String, Part>();
        if (json.has("children")) {
            for (var entry : json.getAsJsonObject("children").entrySet()) {
                children.put(entry.getKey(), parsePart(entry.getValue().getAsJsonObject()));
            }
        }
        return new Part(value(json, "x"), value(json, "y"), value(json, "z"),
            value(json, "xr"), value(json, "yr"), value(json, "zr"), quads, children);
    }

    private static float value(JsonObject json, String key) {
        return json.has(key) ? json.get(key).getAsFloat() : 0;
    }

    /** Emits a part tree at its default pose under the given transform. */
    public static void emit(List<TexturedQuad> out, Part part, Matrix4f parent,
                            TexturePixels texture, int colorMul) {
        emit(out, part, "root", parent, texture, colorMul, Map.of());
    }

    /** Emit with extra X rotations by part name — chest lids, lecterns, anything hinged. */
    public static void emit(List<TexturedQuad> out, Part part, String name, Matrix4f parent,
                            TexturePixels texture, int colorMul, Map<String, Float> extraXRot) {
        emit(out, part, name, parent, texture, colorMul, extraXRot, Map.of());
    }

    /**
     * Emit with hinged X additions and absolute X/Y pose overrides by part
     * name — vanilla poses boat paddles by assignment, not addition.
     */
    public static void emit(List<TexturedQuad> out, Part part, String name, Matrix4f parent,
                            TexturePixels texture, int colorMul, Map<String, Float> extraXRot,
                            Map<String, float[]> poseOverride) {
        // Boats carry an invisible depth-mask part that keeps water out of
        // the hull; rendered as geometry it would lid the boat shut.
        if (name.equals("water_patch")) return;
        var matrix = new Matrix4f(parent).translate(part.x() / 16, part.y() / 16, part.z() / 16);
        var pose = poseOverride.get(name);
        float xr = pose != null ? pose[0] : part.xr() + extraXRot.getOrDefault(name, 0f);
        float yr = pose != null ? pose[1] : part.yr();
        if (part.zr() != 0) matrix.rotateZ(part.zr());
        if (yr != 0) matrix.rotateY(yr);
        if (xr != 0) matrix.rotateX(xr);

        var position = new Vector3f();
        for (var quad : part.quads()) {
            var xs = new float[4];
            var ys = new float[4];
            var zs = new float[4];
            var us = new float[4];
            var vs = new float[4];
            for (int i = 0; i < 4; i++) {
                position.set(quad[i][0] / 16, quad[i][1] / 16, quad[i][2] / 16);
                matrix.transformPosition(position);
                xs[i] = position.x;
                ys[i] = position.y;
                zs[i] = position.z;
                us[i] = quad[i][3];
                vs[i] = quad[i][4];
            }
            out.add(TexturedQuad.ofColored(xs, ys, zs, us, vs, texture, TexturedQuad.TINT_NONE, -1, colorMul));
        }
        for (var child : part.children().entrySet()) {
            emit(out, child.getValue(), child.getKey(), matrix, texture, colorMul, extraXRot, poseOverride);
        }
    }
}
